apiVersion: v1

kind: Service
metadata:
  name: listener
  labels:
    name: listener
spec:
  ports:
    - nodePort: 30111
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: listener
  type: NodePort

---

apiVersion: apps/v1

kind: Deployment
metadata:
  name: listener
spec:
  selector:
    matchLabels:
      app: listener
  replicas: 3
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
        - name: listener
          image: aladdinych/virt5:listener
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres:5432/postgres"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: RABBIT_QUEUE
              value: "rabbitQueue"
            - name: RABBIT_HOST
              value: "rabbitmq"
