apiVersion: v1

kind: Service
metadata:
  name: producer
  labels:
    name: producer
spec:
  ports:
    - nodePort: 30195
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: producer
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  selector:
    matchLabels:
      app: producer
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: aladdinych/virt5:producer
          ports:
            - containerPort: 8080
          env:
            - name: RABBIT_QUEUE
              value: "rabbitQueue"
            - name: RABBIT_HOST
              value: "rabbitmq"
